"""sample upgrade

Revision ID: 48313d54e215
Revises: eea22cf09372
Create Date: 2025-06-03 13:25:11.033547

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '48313d54e215'
down_revision: Union[str, None] = 'eea22cf09372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_table',
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sample_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_table')
    # ### end Alembic commands ###
