"""add subtasks in tasks table

Revision ID: c9d6c067cb83
Revises: eea22cf09372
Create Date: 2025-08-24 19:14:19.528539

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c9d6c067cb83'
down_revision: Union[str, None] = 'eea22cf09372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_parent_task', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('parent_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_parent_task_id', 'tasks', ['parent_task_id'], ['id'])
        batch_op.add_column(sa.Column('is_expanded', sa.Boolean(), nullable=True, default=False))

    op.execute(
        """
        UPDATE tasks
        SET is_expanded = 1
        WHERE is_parent_task = 1 and task_type = 'TODO'
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_parent_task_id', type_='foreignkey')
        batch_op.drop_column('parent_task_id')
        batch_op.drop_column('is_parent_task')
        batch_op.drop_column('is_expanded')

    # ### end Alembic commands ###
