name: Build App

on:
    push:
    workflow_dispatch:

jobs:
    build:
        uses: ./.github/workflows/reusable-build-app.yml
        with:
            deployment: false
            mitmproxy-version: ${{ needs.check-mitmproxy-version.outputs.mitmproxy-version }}
        secrets: inherit
