name: Build and Release App

on:
    push:
        tags:
            - 'v*.*.*'


jobs:
    check-mitmproxy-version:
        uses: ./.github/workflows/check-mitmproxy-version.yml
        secrets: inherit

    build:
        uses: ./.github/workflows/build-app.yml
        needs: check-mitmproxy-version
        with:
            deployment: true
            mitmproxy-version: ${{ needs.check-mitmproxy-version.outputs.mitmproxy-version }}
        secrets: inherit
