name: Build and Release App

on:
    workflow_dispatch:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'

jobs:
    check-mitmproxy-version:
        uses: ./.github/workflows/reusable-check-mitmproxy-version.yml
        secrets: inherit

    build:
        uses: ./.github/workflows/reusable-build-app.yml
        needs: check-mitmproxy-version
        with:
            deployment: true
            mitmproxy-version: ${{ needs.check-mitmproxy-version.outputs.mitmproxy-version }}
        secrets: inherit

    create-installer:
        uses: ./.github/workflows/reusable-create-installer.yml
        needs: build
        with:
            should_sign: ${{ github.event_name != 'workflow_dispatch' }}
        secrets: inherit

    release:
        if: github.event_name != 'workflow_dispatch'
        permissions:
            contents: write  # Required to create releases
        uses: ./.github/workflows/reusable-release-app.yml
        needs: create-installer
        secrets: inherit
