name: Create Installer

on:
    workflow_call:

jobs:
    create-installer:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-22.04, ubuntu-22.04-arm, windows-latest, macos-13, macos-latest ]  # using older
                # ubuntu for compatibility with older linux distros
                # https://nuitka.net/user-documentation/common-issue-solutions.html#linux-standalone
                python-version: [ 3.12 ]
                include:
                    - os: ubuntu-22.04
                      architecture: x86_64
                    - os: ubuntu-22.04-arm
                      architecture: aarch64

        steps:
            -   name: Store Architecture
                run: |
                    if [ "${{ matrix.architecture }}" != "" ]; then
                        echo "ARCHITECTURE=${{ matrix.architecture }}" >> $GITHUB_ENV
                    else
                        ARCHITECTURE=$(uname -m)
                        echo "ARCHITECTURE=$ARCHITECTURE" >> $GITHUB_ENV
                    fi
                shell: bash

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: tree command (Windows)
                if: matrix.os == 'windows-latest'
                run: |
                    Get-ChildItem -Recurse "."

            -   name: Set artifact name
                id: set-artifact
                run: |
                    if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                        echo "artifact_name=macOS_arm64-build" >> $GITHUB_OUTPUT
                    elif [[ "${{ matrix.os }}" == "macos-13" ]]; then
                        echo "artifact_name=macOS_x86_64-build" >> $GITHUB_OUTPUT
                    elif [[ "${{ matrix.os }}" == "ubuntu-22.04" || "${{ matrix.os }}" == "ubuntu-22.04-arm" ]]; then
                        echo "artifact_name=Linux_${{ env.ARCHITECTURE }}-build" >> $GITHUB_OUTPUT
                    elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                        echo "artifact_name=Windows_x86_64-build" >> $GITHUB_OUTPUT
                    fi
                shell: bash

